---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(ProBot)
library(torch)
library(parallel)
library(ParmOff)
```

```{r}
sample_func = function(alpha1, beta1, alpha2, beta2, gamma, n_samp){
  temp = c(rnorm(n_samp*gamma, alpha1, beta1), rnorm(n_samp*(1-gamma), sqrt(alpha2), sqrt(beta2)))
  return(c(mean(temp), var(temp)))
}
```

```{r}
params = cbind(alpha1 = runif(1e5, 1,10),
               beta1 = runif(1e5, 1,10),
               alpha2 = runif(1e5, 1,10),
               beta2 = runif(1e5, 1,10),
               gamma = runif(1e5),
               n_samp = 1e3)
```

```{r}
sim_out = mclapply(1:1e5,
                  function(i){ParmOff(.func=sample_func, .args=as.list(params[i,]))},
                  mc.cores = 20 )
sim_out = do.call(rbind, sim_out)
```
